### ISSUE TITLE
Use standard style

### ISSUE THREAD

**Issue by 1vasari** [plainblack/Lacuna-Web-Client#124]
See http://standardjs.com/

**Comment by dmcbride** [comment]
Um, would rather not.

**Comment by 1vasari** [comment]
@icydee and @dmcbride I'd like to bump this one.

I find it extremely useful to have a linter setup (JSHint, ESLint, standard, whatever) purely because I can get live feedback in my editor as to whether I stuffed up my code or not. I don't need to wait for it to compile for it to tell me that I misspelled a variable or whatever. 

My first preference is standard (or one of it's forks). My second would be setting up ESLint with our preferences.

What do you folks think?

**Comment by icydee** [comment]
I have a few problems with the 'standard'.
1) tab's of 4 works best with code not 2. The only exception to this is that for html tabs of 2 seem to work better because  of the higher levels of indentation.
2) 'no semicolons', disagree violently, this can cause silent bugs, which admittedly the next point (don't start a line with a '(' or a '[') is meant to alleviate. Far better in my opinion to get into the habit of always using semi-colons.
3) space after function name... certainly not. Never have a space after a function name.

Best of the 'good'
use of '===' is good.
no unused variables
space after keywords

So, if it can be configured differently from the standard, then perhaps it would be worth doing.

**Comment by 1vasari** [comment]
Standard uses ESLint under the hood. So I could steal their ESLint config file (whatever it's called) and modify it for our purposes. 

Also, there's a fork of standard called semi-standard which has semicolons. :grinning:

**Comment by dmcbride** [comment]
A linter, in general, I'm fine with.  It was specific issues with 'standard' that I took issue with.  As you may recall, tabs and semicolons were two of the issues.  In perl, I turn on all warnings all the time, and write exceptions on a case-by-case basis.  So, as long as we can signify "linter, I know this doesn't look good, but trust me on this" on the, what I would guess is, *rare* case where we need to, setting up ESLint or whatever is fine.  I assume this would become part of the standard gulp command (no params), which means that you have to pass the lint to test the code, and lint would be run on the servers during deploy.

**Comment by 1vasari** [comment]
I'll figure something out in the build system. 

I think I'll implement a custom ESLint file based off of standard and taking into account icy's feedback and we can go from there.
