### ISSUE TITLE
Ability for admins to switch to account without logging out

### ISSUE THREAD

**Issue by RedOrion** [plainblack/Lacuna-Web-Client#129]
Like in the admin interface display a spot to specify game account and then have option in top bar to switch chatting accounts.

**Comment by dmcbride** [comment]
Not sure we want to switch "chatting" accounts.  The (relatively) trivial fix is to allow a Lacuna::Session to tag an "extra" dynamic baby (this will possibly screw with the SQL, and, even if that's trivial, it may make the whole thing unbearably slow - we'll have to do some test timings here, since mysql has surprised me here with the sitter stuff already).  However, then you'll be more or less limited to whatever the UI allows sitters to do with babies - check their email (except correspondence), check their planets, but not check their stations.

I'll also want this extra API for admins to not only obviously check that this is an admin account :) but also to log the temporary addition of extra powers - like an admin login does now from the admin UI - probably also in the login_log table.

However, if you want *full* access with the other account, then it becomes much more difficult.

**Comment by 1vasari** [comment]
Honestly, I doubt that this would get implemented purely because it sounds like a lot of work for little gain (it only helps the admins).
